[versions] # Gradle versions
shadow = "7.1.2"
licenser = "0.6.1"
lombok = "6.5.0.3"

# Lib versions
gson = "2.10.1"
guava = "31.1-jre"
annotations = "24.0.1"

[plugins]
# Gradle plugins
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries] # Gradle libraries

# serialization
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# annotations
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# condition management
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
